name: notify4j CI
on:
  - push
  - manual
push:
  branches:
    - main
checkout: true
jobs:
  build:
    image: eclipse-temurin:17-jdk
    timeout: 30m
    cache:
      key: m2-notify4j
      paths:
        - .m2/repository
    steps:
      - name: build
        run: ./mvnw -B verify -Pdefault --no-transfer-progress -Dmaven.repo.local=.m2/repository
